# Generated by Django 3.0.6 on 2020-12-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Elearn', '0002_content_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('File', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Student')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
